summpy-api:
  container_name: summpy-api
  image: kuniiskywalker/summpy-api

scraping:
  container_name: scraping
  build: ./scraping
  volumes:
    - "./scraping:/go/src/app"
  command: go run main.go

web:
  container_name: pocket
  restart: always
  build: ./app
  command: bundle exec ruby app.rb -o 0.0.0.0 -p 4368
  # if to not use nginx, ports active
  # ports:
  #  - 80:4368
  volumes:
    - ./app:/app
  links:
    - summpy-api
    - scraping
  environment:
    HTTP_HOST: http://192.168.0.45
    POCKET_CONSUMER_KEY: 53593-6842340df8f29d90783eff1e
    VIRTUAL_HOST: 192.168.0.45 
    VIRTUAL_PORT: 4368
